name: "hello world workflow"

on: 
    push:
        branches:
            - master
            - production

jobs:
    hello_word:
        runs-on: ubuntu-latest
        steps:
            - name: "print hello world"
              run: echo "hello world"

            - name: "print current date"
              run: date


    fruits:
        runs-on: ubuntu-latest
        steps:
            - name: "list of fruits"
              run: echo "Apple Banana Mango Grapes"

            - name: "print date"
              run: date