name: "multi event pipeline/workflow" # name of pipeline

on:
    push:  # Event: Whenever a push is made to the repository on the master/test branch
        branches:
            - master
            - test

    pull_request:  # Event: Whenever a pull-request is made to the repository
        branches:
            - master


jobs:
    on-push: # job name 1
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: # steps to be executed in the job
             - name: "running on push" # step-1
               run: echo "running on push"


    on-pull_request: # job name 2
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps: # steps to be executed in the job
             - name: "running on pull-request" # step-1
               run: echo "running on pull-request"
